// EDIT YOUR REELS HERE
// Put thumbnail files inside the /images folder, then paste each Instagram Reel URL.
const reels = [
 {title:'Wedding Reel 01', thumbnail:'images/pappu.jpg', url:'https://www.instagram.com/reel/DdJHCypxidx/?utm_source=ig_web_copy_link&stkn=MzRlODBiNWFlZA=='},
 {title:'Wedding Reel 02', thumbnail:'images/chai.jpg', url:'https://www.instagram.com/reel/DdJMZCxRDI0/?utm_source=ig_web_copy_link&stkn=MzRlODBiNWFlZA=='},
 {title:'Wedding Reel 03', thumbnail:'images/naam karan.jpg', url:'https://www.instagram.com/reel/DaxfLczIarR/?utm_source=ig_web_copy_link&stkn=MzRlODBiNWFlZA=='},
 {title:'Wedding Reel 04', thumbnail:'images/care.jpg', url:'https://www.instagram.com/reel/DbnlWMytJiQ/?utm_source=ig_web_copy_link&stkn=MzRlODBiNWFlZA=='},
 {title:'Wedding Reel 05', thumbnail:'images/reaction.jpg', url:'https://www.instagram.com/reel/DbTD3NktTYw/?utm_source=ig_web_copy_link&stkn=MzRlODBiNWFlZA=='},
 {title:'Wedding Reel 06', thumbnail:'images/transtition.jpg', url:'https://www.instagram.com/reel/DXuGIMpCOnb/?utm_source=ig_web_copy_link&stkn=MzRlODBiNWFlZA=='}
];
function placeholderData(title){const safe=String(title||'ShaadiVibes').replace(/[<>&'\"]/g,'');const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 1120"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#251d19"/><stop offset="1" stop-color="#0c0a0a"/></linearGradient></defs><rect width="720" height="1120" fill="url(#g)"/><circle cx="530" cy="190" r="210" fill="#d7b18b" opacity=".08"/><text x="60" y="150" fill="#d7b18b" font-family="Arial" font-size="24" letter-spacing="6">SHADIVIBES.IN</text><text x="60" y="540" fill="#f7f1ec" font-family="Georgia,serif" font-size="58">${safe}</text><text x="60" y="1010" fill="#b5aaa4" font-family="Arial" font-size="20" letter-spacing="3">WEDDING CONTENT CREATION</text></svg>`;return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
function renderReels(){const grid=document.getElementById('reelGrid');if(!grid)return;grid.innerHTML=reels.map((reel,index)=>{const title=String(reel.title||`Wedding Reel ${index+1}`).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const thumb=reel.thumbnail&&reel.thumbnail!==`images/reel-0${index+1}.jpg`?reel.thumbnail:placeholderData(title);return `<a class="reel-card" href="${reel.url}" target="_blank" rel="noopener" aria-label="Open ${title} on Instagram"><img src="${thumb}" alt="${title} thumbnail" onerror="this.onerror=null;this.src=placeholderData('${title.replace(/'/g,"\\'")}')"><div class="reel-meta"><div class="reel-title">${title}</div><span class="reel-open">↗</span></div></a>`}).join('')}
renderReels();
const menuBtn=document.querySelector('.menu-btn'),navLinks=document.querySelector('.nav-links');menuBtn?.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuBtn?.setAttribute('aria-expanded','false')}));document.getElementById('year').textContent=new Date().getFullYear();
